#include <CtrlLib/CtrlLib.h>
#include <ProjectMgmt/AK.h>

// This file implements the key definitions from AK.key
// It should be compiled only once to avoid multiple definition errors

// The actual implementation is generated by including key_source.h
#define KEYGROUPNAME "AK"
#define KEYNAMESPACE AKKeys
#define KEYFILE      <ProjectMgmt/AK.key>
#include             <CtrlLib/key_source.h>